name: my_project

packages:
  - src/apps/**
  - src/packages/**
  - src/shared/**

scripts:
  analyze: flutter analyze

  test: flutter test

  ci:
    run: |
      melos run test
      melos run analyze

  build:web:
    run: |
      melos bs
      cd apps/app && flutter build web --release && cd .. && cd ..

  format: dart format .
