name: my_project

packages:
  - feature/**
  - packages/**
  - shared/**
  
scripts:
  analyze:
    exec: dart analyze .

command:
  version: 
    branch: main
    workspaceChangelog: true
    message: |
      chore: cut package releases 🎉

      {new_package_versions}
