name: routing
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  login:
    path: ../../apps/login

  home:
    path: ../../apps/home
